<?php

global $APPLICATION;

$APPLICATION->IncludeComponent(
    "zlabs:feedbackform.form",
    "modal-form",
    array(
        "COMPONENT_TEMPLATE" => "modal-form",
        "id" => "callback-form",
        "title" => "Заказать звонок",
        "sub_title" => "",
        "submit_text" => "Отправить",
        "footnote_text" => "",
        "num_fields" => "1",
        "show_error_messages" => "N",
        "event_message_id" => array(
            0 => "12",
        ),
        "name" => "Глобальная форма \"Заказать звонок\" в подвале сайта",
        "email_to" => array(
            0 => "east.transit@yandex.ru",
        ),
        "goals" => array(),
        "ga_goals" => array(),
        "success_message_title" => "Заявка отправлена",
        "success_message" => "В ближайшее время наши специалисты свяжутся с вами.",
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "1",
        "USER_CONSENT_IS_CHECKED" => "N",
        "USER_CONSENT_IS_LOADED" => "N",
        "field_0_type" => "ZLabs\\Components\\Feedback\\Fields\\TextField",
        "field_0_title" => "Телефон",
        "field_0_code" => "PHONE",
        "field_0_required" => "Y",
        "field_0_placeholder" => "+7 (___) ___-__-__",
        "field_0_note" => "",
        "field_0_mask" => "phone",
        "field_0_label" => "Номер телефона",
        "save_to_iblock" => "Y",
        "ib_model" => ZLabs\Models\Feedback\CallUsFooter::class,
    ),
    false
);

$APPLICATION->IncludeComponent(
	"zlabs:feedbackform.form", 
	"modal-form", 
	array(
		"COMPONENT_TEMPLATE" => "modal-form",
		"id" => "write-form",
		"title" => "Связаться с нами",
		"sub_title" => "",
		"submit_text" => "Отправить",
		"footnote_text" => "",
		"num_fields" => "3",
		"show_error_messages" => "N",
		"event_message_id" => array(
			0 => "12",
		),
		"name" => "Глобальная форма \"Написать нам\" в подвале сайта",
		"email_to" => array(
			0 => "east.transit@yandex.ru",
			1 => "",
		),
		"goals" => array(
		),
		"ga_goals" => array(
		),
		"success_message_title" => "Заявка отправлена",
		"success_message" => "В ближайшее время наши специалисты свяжутся с вами.",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "N",
		"USER_CONSENT_IS_LOADED" => "N",
		"field_0_type" => "ZLabs\\Components\\Feedback\\Fields\\TextField",
		"field_0_title" => "Телефон",
		"field_0_code" => "PHONE",
		"field_0_required" => "Y",
		"field_0_placeholder" => "+7 (___) ___-__-__",
		"field_0_note" => "",
		"field_0_mask" => "phone",
		"field_0_label" => "Номер телефона",
		"field_1_type" => "ZLabs\\Components\\Feedback\\Fields\\TextField",
		"field_1_title" => "Имя",
		"field_1_code" => "NAME",
		"field_1_required" => "Y",
		"field_1_placeholder" => "",
		"field_1_note" => "",
		"field_1_mask" => "simple",
		"field_1_label" => "Имя",
		"field_2_type" => "ZLabs\\Components\\Feedback\\Fields\\TextAreaField",
		"field_2_title" => "Сообщение",
		"field_2_code" => "MESSAGE",
		"field_2_required" => "N",
		"field_2_placeholder" => "",
		"field_2_note" => "",
		"field_2_label" => "Сообщение",
        "save_to_iblock" => "Y",
        "ib_model" => ZLabs\Models\Feedback\MessageUsFooter::class,
	),
	false
);

$APPLICATION->IncludeComponent(
    "zlabs:feedbackform.form",
    "modal-form",
    array(
        "COMPONENT_TEMPLATE" => "modal-form",
        "id" => "global-consul",
        "title" => "Получить консультацию",
        "sub_title" => "",
        "submit_text" => "Отправить",
        "footnote_text" => "",
        "num_fields" => "3",
        "show_error_messages" => "N",
        "event_message_id" => array(
            0 => "12",
        ),
        "name" => "Глобальная форма \"Написать нам\" в подвале сайта",
        "email_to" => array(
            0 => "east.transit@yandex.ru",
            1 => "",
        ),
        "goals" => array(
        ),
        "ga_goals" => array(
        ),
        "success_message_title" => "Заявка отправлена",
        "success_message" => "В ближайшее время наши специалисты свяжутся с вами.",
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "1",
        "USER_CONSENT_IS_CHECKED" => "N",
        "USER_CONSENT_IS_LOADED" => "N",
        "field_0_type" => "ZLabs\\Components\\Feedback\\Fields\\TextField",
        "field_0_title" => "Имя",
        "field_0_code" => "NAME",
        "field_0_required" => "Y",
        "field_0_placeholder" => "",
        "field_0_note" => "",
        "field_0_mask" => "simple",
        "field_0_label" => "Имя",

        "field_1_type" => "ZLabs\\Components\\Feedback\\Fields\\TextField",
        "field_1_title" => "Телефон",
        "field_1_code" => "PHONE",
        "field_1_required" => "Y",
        "field_1_placeholder" => "+7 (___) ___-__-__",
        "field_1_note" => "",
        "field_1_mask" => "phone",
        "field_1_label" => "Номер телефона",

        "field_2_type" => "ZLabs\\Components\\Feedback\\Fields\\TextAreaField",
        "field_2_title" => "Сообщение",
        "field_2_code" => "MESSAGE",
        "field_2_required" => "N",
        "field_2_placeholder" => "Ваш вопрос",
        "field_2_note" => "",
        "field_2_label" => "Сообщение",
        "save_to_iblock" => "Y",
        "ib_model" => ZLabs\Models\Feedback\ConsulHeader::class,
    ),
    false
);